"""referrals + beta access

Revision ID: 7fd086732113
Revises: d0775f984214
Create Date: 2026-07-08 20:43:23.576776

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fd086732113'
down_revision: Union[str, Sequence[str], None] = 'd0775f984214'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add columns as nullable / with defaults first so existing rows are valid
    op.add_column('waitlist', sa.Column('referral_code', sa.String(length=12), nullable=True))
    op.add_column('waitlist', sa.Column('referred_by_code', sa.String(length=12), nullable=True))
    op.add_column('waitlist', sa.Column('referral_count', sa.Integer(), nullable=False, server_default='0'))
    op.add_column('waitlist', sa.Column('beta_access', sa.Boolean(), nullable=False, server_default=sa.false()))

    # Backfill referral_code for existing rows using a short random hex
    op.execute("UPDATE waitlist SET referral_code = UPPER(SUBSTR(REPLACE(gen_random_uuid()::text, '-', ''), 1, 8)) WHERE referral_code IS NULL")

    # Now enforce NOT NULL + uniqueness
    op.alter_column('waitlist', 'referral_code', nullable=False)
    op.create_index(op.f('ix_waitlist_beta_access'), 'waitlist', ['beta_access'], unique=False)
    op.create_index(op.f('ix_waitlist_referral_code'), 'waitlist', ['referral_code'], unique=True)
    op.create_index(op.f('ix_waitlist_referred_by_code'), 'waitlist', ['referred_by_code'], unique=False)
    op.create_foreign_key(None, 'waitlist', 'waitlist', ['referred_by_code'], ['referral_code'])


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'waitlist', type_='foreignkey')
    op.drop_index(op.f('ix_waitlist_referred_by_code'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_referral_code'), table_name='waitlist')
    op.drop_index(op.f('ix_waitlist_beta_access'), table_name='waitlist')
    op.drop_column('waitlist', 'beta_access')
    op.drop_column('waitlist', 'referral_count')
    op.drop_column('waitlist', 'referred_by_code')
    op.drop_column('waitlist', 'referral_code')
    # ### end Alembic commands ###
